[package]
authors = ["biblius <crazycompanyxxl@gmail.com>"]
categories = ["validation"]
description = "An extension of the validator crate that enables payload modification"
edition = "2021"
exclude = ["derive_validify_tests/"]
homepage = "https://github.com/biblius/validify"
keywords = ["modify", "validate", "validation", "validify"]
license = "MIT"
name = "validify"
readme = "README.md"
repository = "https://github.com/biblius/validify"
version = "0.1.0"

[dependencies]
derive_validify = { path = "../derive_validify" }
proc-macro2 = "1.0.47"
syn = { version = "1.0.103", features = ["full"] }
traits = { path = "../traits" }
validator = { version = "0.16.0", features = ["derive"] }
