[package]
edition = "2021"
name = "derive_validator"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
lazy_static = "1"
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
regex = "1.5.5"
syn = { version = "1", features = ["extra-traits"] }
types = { path = "../types" }
